id: ecology-mysql-config

info:
  name: Fanwei OA E-Office - Information Disclosure
  author: ritikchaddha
  severity: medium
  description: 文件可直接访问，泄露数据库帐号密码等信息。
  metadata:
    max-request: 1
    verified: true
    fofa-query: app="泛微-EOffice"
  tags: fanwei,ecology,exposure,config

http:
  - method: 
      - GET
    path:
      - "{{BaseURL}}/mysql_config.ini"

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - "dataurl"
          - "datapassword"
          - "datauser"
        condition: and


      - type: status
        status:
          - 200
